### ISSUE TITLE
Concepts Feedback

### ISSUE THREAD

**Issue by brandonbrown** [fs-tech-degs/capstone-kari-mashburn#1]
> This is a copy of my message from Discord for archiving and open-discussion

We are going to have to reject Cuddly. The potential for that to inadvertently turn into a different kind of app is something we can't have happening from a Full Sail class. 

For the other idea, we'd want more research into the background check source. It's easy for these types of services to be nothing more than social security gathering databases and not truly perform their action. Make sure to pour some time into researching this.

It was also requested that as part of your final tech stack decision, you explain why you would like to use mongo vs a relational database solution.

**Comment by kari-mashburn** [comment]
Hello Brandon,

The reasons why I want to use MongoDB over a relational database is because MongoDB is able to hold location-based data really well and my application will be relying on the user's' housing location to make sure it finds the right matches between the users. Another reason is, Mongo provides validation on the database side, which helps the server-side mongoose validation and the client-side validation. With MongoDB, I'm able to query faster because most of the data will be in a single document rather than in SQL where the data could be in multiple tables and would take longer to query. MongoDB utilizes a flexible schema, meaning you can drop documents within a collection, and it isn’t necessary to have any relations between those documents. The only restriction being supported data structures. In order to store anything in MySQL, you need to clearly define tables, and every row in the table should have the same column. This makes it so there isn’t much space for flexibility in terms of storing data if you follow normalization.
After doing some research on the companies that use MongoDB, a lot of them would explain how MongoDB has made their company a lot better by their support of multi-document ACID transactions, it has the speed, flexibility, and power of the document model with ACID guarantees. Coinbase is one of many top companies and one of their case studies is here: [MongoDB Coinbase Case-Study](https://www.mongodb.com/customers/coinbase )

Also per our discussion in class, we talked about the FindMyRoomie application, the following ideas were thrown around: 

- Integrate the social media profiles so users can view their profiles before making a decision for making them a prospective roommate. 

- Research dating applications so that I can get an idea on how they create matches between users

- Connecting the user's address to the API to verify that the user does indeed live there so that it prevents any scams that users could potentially do

- Once two matches meet up in a neutral location, the user creating the ad will be able to unlock their listing to the potential roommate so that they are able to access and get more information on the property

- For locations use the MapBox API instead of the Google Maps API

- The ability to review the roommate reviews, such as it can be flagged if the review has nothing to do with the user as a roommate or the ad in general.
